name: Build & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LBRY version'
        required: true
  pull_request:
    branches:
      - master

env:
  # LBRY_VERSION: ${{ github.event.inputs.version }}
  LBRY_VERSION: 0.17.1
  SCRIPTS_BRANCH: change-api-link

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Release
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: lbryio/lbry-android
          ref: ${{ env.LBRY_VERSION }}
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '13'
          cache: gradle
      - name: Install `zipalign`
        run: |
          sudo apt-get update
          sudo apt-get install -y zipalign
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r16b
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          wget https://raw.githubusercontent.com/paveloom-f/lbry-android/${{ env.SCRIPTS_BRANCH }}/.github/scripts/build_a_release.bash 2>/dev/null
          chmod +x build_a_release.bash
          ./build_a_release.bash
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APKs
          path: |
            bin/LBRY_arm.apk
            bin/LBRY_arm64.apk
      # - name: Delete the previous release (if exists)
      #   run: |
      #     wget https://raw.githubusercontent.com/paveloom-f/lbry-android/${{ env.SCRIPTS_BRANCH }}/.github/scripts/delete_a_release.bash 2>/dev/null
      #     chmod +x delete_a_release.bash
      #     ./delete_a_release.bash
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_PAT }}
      #     GH_REPO: https://api.github.com/repos/paveloom-f/lbry-android/releases
      # - name: Create a release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     body: Use at your own risk.
      #     name: ${{ env.LBRY_VERSION }}
      #     tag_name: v${{ env.LBRY_VERSION }}
      #     files: |
      #       bin/LBRY_arm.apk
      #       bin/LBRY_arm64.apk
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
